export const programsList: string[] = ['Agricultural and Food Sciences',
  'Agriculture Diploma',
  'Architecture',
'Arts',
'Education',
'Engineering',
'Environment, Earth and Resources',
'Extended Education (General Studies)',
'Fine Arts',
'Health Sciences (Interdisciplinary Health)',
'Kinesiology & Recreation Management',
'Management - Asper School of Business',
'Medicine (Family Social Sciences)',
'Medicine (Other)',
'Music',
'Nursing',
'Pharmacy (BSc.)',
'Rehabilitation Sciences',
'Science',
'Social Work'];
